import "../styles/globals.css";
import { Header } from "@/components/layouts/Header";
import { Footer } from "@/components/layouts/Footer";
import "bootstrap-icons/font/bootstrap-icons.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

      <div className="flex flex-col h-screen">
        <Header className="w-full shrink-0" />
        
        <main className="flex flex-grow overflow-hidden">
          {children}
        </main>
        
        <Footer className="w-full" />
      </div>

//         <div className="flex flex-col min-h-screen">
//           <Header className="w-full" />
//           <main className="flex flex-grow">{children}</main>

//           <Footer className="w-full" />
//         </div>
      </body>
    </html>
  );
}
