import '../styles/globals.css'
import { Header } from "@/components/layouts/Header"
import { Footer } from "@/components/layouts/Footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <>
      <div className="flex flex-col min-h-screen">
        <Header className="w-full" />
        
        <main className="flex flex-grow">
          {children}
        </main>
        
        <Footer className="w-full" />
      </div>
      </>
    </html>
  )
}
